- name: Install app dependencies
  apt: name={{item}} state=present
  with_items:
    - git
    - build-essential
    - libxml2-dev
    - libxslt-dev
    - libxslt1-dev
    - libssl-dev
    - zlib1g-dev
    - liblzma-dev
    - libmagick-dev
    - curl
    - libpq-dev
    - libreadline-dev
    - libyaml-dev
    - nodejs

- include: nginx.yml
- include: puma.yml